language: ruby
rvm:
- 2.0
- 2.1
- 2.2
env:
  matrix:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
  global:
  - secure: A7qL+lmkql4NRXzHa9P5dBAkaGCRJldBl+HGThsywmBJaYAfDEczhKdCkz6uE7TfpXoXxNoWjRB9aM9idF+1BV30I+sjh8xKVwgbL/GyfGmvB8evDmtdZZ1TKiSswFHSpnoyUe2pIc+Z2kKbzRoXYMQk+695iIoqE3JNWk4ZCD4=
  - secure: hpeoIPRPlCvj5wkrjgUMjwI8ua6EI6XF7Wn/Ul+B+PmPgWQIjV2knpDxpS2WVrbrF0lnY2naDm9tSEkL0RXPy8PKZZAurj5hWvzbaEAfdXRUeyf0xQ4jz1UDXGjp+ehzFdasRyBsDAyTLgzA7hr3u0kU0Ol+oxDvyXBNC9QbFvg=
  - secure: Hoi5/9h9JpdCEBk0AgbKhnwMumxw6YX0iMchpUk3lN1agboTbf/UZdEPkEJBOcWJrpyQahamv5Vmqzq5hSh22fvRRdRbiCL9BjSL38cjOU7TQ52fXHYU1uFOf5MFUHUeghV0cSmoMAYcEkXKoccXPpIjpuz+ND7kIUDVqRZ+xz4=
  - secure: KMLK+vtKRUG7epJZuKwu+3ca+Z5of9weU3jGZei8jUiQnuVC6vFgga1wwk+5EMKxybHjFzkj6Yis9xnegEQYqC0CzrCnQjRvBj8yguubbKmI0jWagrzV7jvPljIZV1gR3oJQU31nUAJQdkDENfA3ClJDGfPCEtQZX1+AzBo5s7E=
before_script:
- cp config/database.test.yml config/database.yml
- cp .env.example .env
- bundle install
script:
- RAILS_ENV=test bin/rake db:create --trace
- RAILS_ENV=test bin/rake db:migrate --trace
- RAILS_ENV=test bin/rake emoji
- RAILS_ENV=test bin/rake spec --trace
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7e569f9f53d7c2c902a9
  on_success: always
  on_failure: always
  on_start: false
